### PR TITLE
 Advance DID Resolution to "Released Draft 0.1.0" 

### PR DESCRIPTION
**Pull request by peacekeeper**

### CODE REVIEW

**Comment by jandrieu** [comment]
This should still be a released draft until we get formal consensus and/or blessing from the chairs. 

We can do that. However, it was my understanding that this is a Released Draft.

The main difference is that Released Drafts are under the control of the editors (just up the version and call it a released draft). Published Drafts are output of the CCG and are posted on the W3C site. As such, they are under the control of the chairs, who generally would look for a period of feedback and consensus on the weekly call and email before formally publishing.

Is this ready for publication or is this still an editor's draft?

**Comment by peacekeeper** [comment]
I'm definitely NOT recommending this for Published Draft, only as Released Draft.

Is the PR wrong? It changes the "Current Stage" field from "Unreleased Draft" to "Released Draft".

What should the "Next Stage" column say?

**Comment by peacekeeper** [comment]
> First, the numbering should be SemVer http://semver.org

The tag I added to the repo is `v0.1.0`: https://github.com/w3c-ccg/did-resolution/releases.

Should the ReSpec document also say `v0.1.0`? E.g. the DID Spec just says `v0.13`, not `v0.13.0`, so I did the same for the DID Resolution Spec.

> Second, a released draft should be in ReSpec, markdown, or bikeshed (with a publication to markdown). Linking to Google doesn't meet the goal of having a version controlled version of the release on Github.

The first column links to the ReSpec on Github Pages, e.g. "DID Resolution" links to: https://w3c-ccg.github.io/did-resolution/

The second column links to the Github repo.

The third+fourth columns link to a Google Doc, which explains the stages of the Work Item process.

**Comment by jandrieu** [comment]
Ok. Great. I just keep misreading the markdown and saw all the google links.

So we just need the version in the table to match the tag. No need to update the PR title, but the work items.md should say 0.1.0.

**Comment by peacekeeper** [comment]
I updated the PR to say `0.1.0`.

**Comment by jandrieu** [comment]
Looks good to me. @ChristopherA @kimdhamilton ?

**Comment by peacekeeper** [comment]
@ChristopherA I thought there's a difference between "released" work items (= there's at least one release tag in the Github repo) and "published" work items (= listed on the CCG page). My sense is that DID Resolution is a bit too early to "publish".

**Comment by ChristopherA** [comment]
Yes, you are correct. But we should change repo description to say Released.

**Pull request merged**
